### ISSUE TITLE
Странная работа программы

### ISSUE THREAD

**Issue by Stone-by** [x73495/travel-assistant-screwed#1]
1) Запустил.
2) Новости.
3) Россия.
4)
![image](https://user-images.githubusercontent.com/56612976/134774877-fb93325e-c59d-42c3-9f07-6026fa50ea0e.png)
5) Так же при повторном запуске программа выдает туже новость. Полагаю, обновление происходят только при перезапуске программы полностью

**Comment by x73495** [comment]
Замечание было рассмотрено и будет исправлено в следующей версии программы - `v0.0-null`

Следите за обновлениями!
