### ISSUE TITLE
Странная работа прогаммы.

### ISSUE THREAD

**Issue by Stone-by** [x73495/travel-assistant-screwed#2]
1) У вас местами перепутаны новости России и Германии, братцы)
2) 
![image](https://user-images.githubusercontent.com/56612976/134774957-b75db135-76d0-42e2-9870-32a7a3361c7c.png)

**Comment by x73495** [comment]
Замечание было рассмотрено и будет исправлено в следующей версии программы - `v0.0-null`

Следите за обновлениями!
