### ISSUE TITLE
Так вырежьте тогда кнопку.

### ISSUE THREAD

**Issue by Stone-by** [x73495/travel-assistant-screwed#3]
1)
![image](https://user-images.githubusercontent.com/56612976/134774999-762e7bec-4a6e-447c-91da-b85dcc4f6823.png)
2) И при чем здесь это вообще?! При нажатии на  Погода->Россия мне кидает ссылку на вот это.
![image](https://user-images.githubusercontent.com/56612976/134775061-808ae0fe-8220-4517-af08-f2fb23b7adda.png)

**Comment by x73495** [comment]
Замечание было рассмотрено и будет исправлено в следующей версии программы - `v0.0-null`

Следите за обновлениями!
